name: Lighthouse CI
on: 
  workflow_dispatch:
  schedule:
    - cron: '* * * * 0,1,2,3,4,5,6'
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g @lhci/cli@0.11.x
      - run: ./collect-report
      - run: git add .
      - run: git commit -m "Lighthouse reports"
      - run: git push origin HEAD:main

